apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-robo
  labels:
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue-robo
        image: primepossum/catalogue-robo
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: {{ .Values.mango_url }}
        - name: MONGO
          value: "true"
